-------------------------------------------------------------------------------
--                                                                           --
--                          GNU Ada Database Tools                           --
--                                                                           --
--                                 GNU.DB                                    --
--                                                                           --
--                                 S P E C                                   --
--                                                                           --
-------------------------------------------------------------------------------
--  Copyright (c) 2001
--  by Juergen Pfeifer
--
--  GNU Ada Database Tools are free software; you can redistribute them      --
--  and/or modify them under terms of the GNU General Public License as      --
--  published by the Free Software  Foundation;  either version 2, or (at    --
--  your option) any later version. GNU Ada Database tools are distributed   --
--  in the hope that they will be useful, but WITHOUT ANY WARRANTY; without  --
--  even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR --
--  PURPOSE. See the GNU General Public License for more details. You should --
--  have received a copy of the GNU General Public License  distributed with --
--  GNU Ada Database Tools;  see file COPYING. If not, write to the          --
--  Free Software Foundation,  59 Temple Place - Suite 330,  Boston,         --
--  MA 02111-1307, USA.                                                      --
--                                                                           --
--  As a special exception,  if other files  instantiate  generics from this --
--  unit, or you link  this unit with other files  to produce an executable, --
--  this  unit  does not  by itself cause the resulting executable to be     --
--  covered  by the  GNU  General  Public  License. This exception does not  --
--  however invalidate  any other reasons why  the executable file  might be --
--  covered by the  GNU Public License.                                      --
--                                                                           --
-------------------------------------------------------------------------------
--  Author: Juergen Pfeifer <juergen.pfeifer@gmx.net>
-------------------------------------------------------------------------------
--
--  This is the root of all the GNU Ada Datbase Tools.
--
--  If you intend to put your own package under the GNU hierarchy, please
--  contact us in advance. Our intention is to develop a coherent and
--  comprehensive set of packages under this root package, so there is
--  a need for some coordination.
--
package GNU.DB is
   pragma Pure (GNU.DB);
end GNU.DB;
